AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  CreateEpisodeHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.logicway.aws.demo.handler.episode.CreateEpisodeHandler
      Runtime: java8
      FunctionName: CreateEpisodeHandler
      MemorySize: 192
      Timeout: 15
      Role: 'arn:aws:iam::654284801655:role/lambda_basic_execution'
      CodeUri: 's3://dafuq-jars/aws-demo-1.0.jar'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /api/episodes/add
            Method: post
      Tags:
        Entity: Episode
  GetEpisodeHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.logicway.aws.demo.handler.episode.GetEpisodeHandler
      Runtime: java8
      FunctionName: GetEpisodeHandler
      MemorySize: 192
      Timeout: 15
      Role: 'arn:aws:iam::654284801655:role/lambda_basic_execution'
      CodeUri: 's3://dafuq-jars/aws-demo-1.0.jar'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /api/episodes/add
            Method: post
      Tags:
        Entity: Episode
  userTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      AttributeDefinitions:
        PrimaryKey:
          Name: id
          Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Users
  storyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 7
        WriteCapacityUnits: 3
      TableName: Stories
  episodeTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 7
        WriteCapacityUnits: 3
      TableName: Episodes
