package com.logicway.aws.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;
import java.util.Map;

@DynamoDBTable(tableName="Episodes")
public class Episode {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String storyId;
    private Integer number;
    private Map<String, Object> textjson;
    private String description;
    private Date availableAt;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getStoryId() {
        return storyId;
    }

    public void setStoryId(String storyId) {
        this.storyId = storyId;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.M)
    public Map<String, Object> getTextjson() {
        return textjson;
    }

    @JsonProperty("textjson")
    public void setTextjson(Map<String, Object> textjson) {
        this.textjson = textjson;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getAvailableAt() {
        return availableAt;
    }

    public void setAvailableAt(Date availableAt) {
        this.availableAt = availableAt;
    }
}
