package com.logicway.aws.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName="Stories")
public class Story {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String name;
    private String image;
    private Date availableAt;
    private Integer hidden;
    private String backgroundcolor;
    private String foregroundcolor;
    private String minuserlevel;
    private String tags;
    private String locale;
    private Integer rating;
    private String theme;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Date getAvailableAt() {
        return availableAt;
    }

    public void setAvailableAt(Date availableAt) {
        this.availableAt = availableAt;
    }

    public Integer getHidden() {
        return hidden;
    }

    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    public String getBackgroundcolor() {
        return backgroundcolor;
    }

    public void setBackgroundcolor(String backgroundcolor) {
        this.backgroundcolor = backgroundcolor;
    }

    public String getForegroundcolor() {
        return foregroundcolor;
    }

    public void setForegroundcolor(String foregroundcolor) {
        this.foregroundcolor = foregroundcolor;
    }

    public String getMinuserlevel() {
        return minuserlevel;
    }

    public void setMinuserlevel(String minuserlevel) {
        this.minuserlevel = minuserlevel;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getLocale() {
        return locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
    }

    public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }
}
